### ISSUE TITLE
Verification tickets not being created

### ISSUE THREAD

**Issue by gombik42** [Yoshod/Sersi#130]
```
Nov 05 16:26:38 localhost python3[118159]: Ignoring exception in on_interaction
Nov 05 16:26:38 localhost python3[118159]: Traceback (most recent call last):
Nov 05 16:26:38 localhost python3[118159]:   File "/home/sersi/.local/lib/python3.10/site-packages/nextcord/client.py", line 499, in _run_event
Nov 05 16:26:38 localhost python3[118159]:     await coro(*args, **kwargs)
Nov 05 16:26:38 localhost python3[118159]:   File "/home/sersi/Live/cogs/tickets.py", line 244, in on_interaction
Nov 05 16:26:38 localhost python3[118159]:     await interaction.response.send_modal(VerificationTicket(self.config))
Nov 05 16:26:38 localhost python3[118159]:   File "/home/sersi/.local/lib/python3.10/site-packages/nextcord/interactions.py", line 939, in send_modal
Nov 05 16:26:38 localhost python3[118159]:     raise InteractionResponded(self._parent)
Nov 05 16:26:38 localhost python3[118159]: nextcord.errors.InteractionResponded: This interaction has already been responded to before
```

**Comment by gombik42** [comment]
fixed
