### ISSUE TITLE
Tickets Open For Too Long Cannot Be Closed

### ISSUE THREAD

**Issue by Yoshod** [Yoshod/Sersi#133]
A ticket that has been open for a long (but undetermined) length of time cannot be closed by Sersi and will interaction fail.

**Comment by Yoshod** [comment]
Dec 20 13:54:54 localhost python3[118159]: Ignoring exception in on_interaction
Dec 20 13:54:54 localhost python3[118159]: Traceback (most recent call last):
Dec 20 13:54:54 localhost python3[118159]:   File "/home/sersi/.local/lib/python3.10/site-packages/nextcord/client.py", line 499, in _run_event
Dec 20 13:54:54 localhost python3[118159]:     await coro(*args, **kwargs)
Dec 20 13:54:54 localhost python3[118159]:   File "/home/sersi/Live/cogs/tickets.py", line 261, in on_interaction
Dec 20 13:54:54 localhost python3[118159]:     await ticketutils.ticket_close(self.config, interaction, user, "admin_ticket")
Dec 20 13:54:54 localhost python3[118159]:   File "/home/sersi/Live/ticketutils.py", line 162, in ticket_close
Dec 20 13:54:54 localhost python3[118159]:     if user.id in ticketers["admin tickets"]:
Dec 20 13:54:54 localhost python3[118159]: AttributeError: 'NoneType' object has no attribute 'id'

**Comment by Yoshod** [comment]
Fixed in unknown commit
