### ISSUE TITLE
[BUG] Ban Vote Not Creating Ban Moderation Log

### ISSUE THREAD

**Issue by Yoshod** [Yoshod/Sersi#186]
**Describe the bug**
A user who has been banned via a moderation ban vote has not had a ban message sent to the Mod Logs or Sersi Logs.

**To Reproduce**
1. Initiate a vote ban
2. Ban the user
3. No message

**Expected behavior**
An embed outlining the ban should be sent to the logs.

**Additional context**
There are logs for ban votes in the testing server so perhaps a new update broke them?

**Comment by Yoshod** [comment]
Issue appears to the result of the following error:
`Ignoring exception in on_vote_ban
Traceback (most recent call last):
  File "/home/sersi/.local/lib/python3.10/site-packages/nextcord/client.py", line 497, in _run_event
    await coro(*args, **kwargs)
  File "/home/sersi/Live/cogs/moderation/ban.py", line 731, in on_vote_ban
    yes_list = "\n• ".join(yes_voters)
TypeError: sequence item 0: expected str instance, int found`

Should be fixed in 5eb2368
